language: android
android:
    components:
        - build-tools-29.0.0
        - android-29
before_install:
    - sudo apt-get install -y python3-pip
    # download citools scripts
    - wget https://raw.githubusercontent.com/Immueggpain/citools/master/decodebase64env.py
    - python3 decodebase64env.py "KEYSTORE" "android.jks"
after_success:
    - pwd
    - mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/forwardproto-android-$TRAVIS_TAG.apk
before_deploy:
    # install PyGithub
    - sudo pip3 install PyGithub
    # download citools scripts
    - wget https://raw.githubusercontent.com/Immueggpain/citools/master/githubrelease.py
    - pwd
deploy:
    provider: script
    script: python3 githubrelease.py "app/build/outputs/apk/release/forwardproto-android-$TRAVIS_TAG.apk"
    skip_cleanup: true
    on:
        tags: true
